[features]
seeds = false
[programs.localnet]
coin_flip = "6Be5Dyf1P4fSjZ7VzA9wiGt44Dpa79nY1Xqt95vsYH8o"
[programs.devnet]
coin_flip = "6Be5Dyf1P4fSjZ7VzA9wiGt44Dpa79nY1Xqt95vsYH8o"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/mnt/d/Projects/Solana/Config/keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
